// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: assistant_provider_states.sql

package db

import (
	"context"
)

const createAssistantProviderState = `-- name: CreateAssistantProviderState :exec
INSERT INTO assistant_provider_states (message_id, provider_id, model_id, state)
VALUES (?, ?, ?, ?)
ON CONFLICT (message_id, provider_id, model_id)
DO UPDATE SET state = excluded.state
`

type CreateAssistantProviderStateParams struct {
	MessageID  string `json:"message_id"`
	ProviderID string `json:"provider_id"`
	ModelID    string `json:"model_id"`
	State      string `json:"state"`
}

func (q *Queries) CreateAssistantProviderState(ctx context.Context, arg CreateAssistantProviderStateParams) error {
	_, err := q.db.ExecContext(ctx, createAssistantProviderState,
		arg.MessageID,
		arg.ProviderID,
		arg.ModelID,
		arg.State,
	)
	return err
}

const deleteAssistantProviderStatesBySession = `-- name: DeleteAssistantProviderStatesBySession :exec
DELETE FROM assistant_provider_states
WHERE message_id IN (SELECT id FROM messages WHERE session_id = ?)
`

func (q *Queries) DeleteAssistantProviderStatesBySession(ctx context.Context, sessionID string) error {
	_, err := q.db.ExecContext(ctx, deleteAssistantProviderStatesBySession, sessionID)
	return err
}

const listAssistantProviderStatesBySession = `-- name: ListAssistantProviderStatesBySession :many
SELECT assistant_provider_states.message_id,
       assistant_provider_states.provider_id,
       assistant_provider_states.model_id,
       assistant_provider_states.state
FROM assistant_provider_states
JOIN messages ON messages.id = assistant_provider_states.message_id
WHERE messages.session_id = ?
`

type ListAssistantProviderStatesBySessionRow struct {
	MessageID  string `json:"message_id"`
	ProviderID string `json:"provider_id"`
	ModelID    string `json:"model_id"`
	State      string `json:"state"`
}

func (q *Queries) ListAssistantProviderStatesBySession(ctx context.Context, sessionID string) ([]ListAssistantProviderStatesBySessionRow, error) {
	rows, err := q.db.QueryContext(ctx, listAssistantProviderStatesBySession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAssistantProviderStatesBySessionRow{}
	for rows.Next() {
		var i ListAssistantProviderStatesBySessionRow
		if err := rows.Scan(
			&i.MessageID,
			&i.ProviderID,
			&i.ModelID,
			&i.State,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
