// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: inbox.sql

package db

import (
	"context"
	"database/sql"
)

const claimInboxMessageForProcess = `-- name: ClaimInboxMessageForProcess :one
UPDATE inbox_messages
SET
    process_attempts = process_attempts + 1,
    updated_at = ?
WHERE id = ?
  AND status = 'archived'
  AND archive_reason = 'replied'
  AND processed_at IS NULL
  AND deleted_at IS NULL
  AND process_attempts < ?
RETURNING id, title, body, workspace_id, job_id, session_id, status, archive_reason, user_reply, processed_at, process_error, process_attempts, archived_at, deleted_at, created_at, updated_at
`

type ClaimInboxMessageForProcessParams struct {
	UpdatedAt       int64  `json:"updated_at"`
	ID              string `json:"id"`
	ProcessAttempts int64  `json:"process_attempts"`
}

func (q *Queries) ClaimInboxMessageForProcess(ctx context.Context, arg ClaimInboxMessageForProcessParams) (InboxMessage, error) {
	row := q.db.QueryRowContext(ctx, claimInboxMessageForProcess, arg.UpdatedAt, arg.ID, arg.ProcessAttempts)
	var i InboxMessage
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Body,
		&i.WorkspaceID,
		&i.JobID,
		&i.SessionID,
		&i.Status,
		&i.ArchiveReason,
		&i.UserReply,
		&i.ProcessedAt,
		&i.ProcessError,
		&i.ProcessAttempts,
		&i.ArchivedAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countOpenInboxMessages = `-- name: CountOpenInboxMessages :one
SELECT COUNT(*)
FROM inbox_messages
WHERE status = 'open'
  AND deleted_at IS NULL
`

func (q *Queries) CountOpenInboxMessages(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countOpenInboxMessages)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createInboxMessage = `-- name: CreateInboxMessage :one
INSERT INTO inbox_messages (
    id,
    title,
    body,
    workspace_id,
    job_id,
    session_id,
    status,
    created_at,
    updated_at
)
VALUES (?, ?, ?, ?, ?, ?, 'open', ?, ?)
RETURNING id, title, body, workspace_id, job_id, session_id, status, archive_reason, user_reply, processed_at, process_error, process_attempts, archived_at, deleted_at, created_at, updated_at
`

type CreateInboxMessageParams struct {
	ID          string         `json:"id"`
	Title       string         `json:"title"`
	Body        string         `json:"body"`
	WorkspaceID sql.NullString `json:"workspace_id"`
	JobID       sql.NullString `json:"job_id"`
	SessionID   sql.NullString `json:"session_id"`
	CreatedAt   int64          `json:"created_at"`
	UpdatedAt   int64          `json:"updated_at"`
}

func (q *Queries) CreateInboxMessage(ctx context.Context, arg CreateInboxMessageParams) (InboxMessage, error) {
	row := q.db.QueryRowContext(ctx, createInboxMessage,
		arg.ID,
		arg.Title,
		arg.Body,
		arg.WorkspaceID,
		arg.JobID,
		arg.SessionID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i InboxMessage
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Body,
		&i.WorkspaceID,
		&i.JobID,
		&i.SessionID,
		&i.Status,
		&i.ArchiveReason,
		&i.UserReply,
		&i.ProcessedAt,
		&i.ProcessError,
		&i.ProcessAttempts,
		&i.ArchivedAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteExpiredInboxMessages = `-- name: DeleteExpiredInboxMessages :execrows
DELETE FROM inbox_messages
WHERE archived_at IS NOT NULL
  AND archived_at < ?
`

func (q *Queries) DeleteExpiredInboxMessages(ctx context.Context, archivedAt sql.NullInt64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteExpiredInboxMessages, archivedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const dismissInboxMessage = `-- name: DismissInboxMessage :one
UPDATE inbox_messages
SET
    status = 'archived',
    archive_reason = 'dismissed',
    archived_at = ?,
    updated_at = ?
WHERE id = ?
  AND status = 'open'
  AND deleted_at IS NULL
RETURNING id, title, body, workspace_id, job_id, session_id, status, archive_reason, user_reply, processed_at, process_error, process_attempts, archived_at, deleted_at, created_at, updated_at
`

type DismissInboxMessageParams struct {
	ArchivedAt sql.NullInt64 `json:"archived_at"`
	UpdatedAt  int64         `json:"updated_at"`
	ID         string        `json:"id"`
}

func (q *Queries) DismissInboxMessage(ctx context.Context, arg DismissInboxMessageParams) (InboxMessage, error) {
	row := q.db.QueryRowContext(ctx, dismissInboxMessage, arg.ArchivedAt, arg.UpdatedAt, arg.ID)
	var i InboxMessage
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Body,
		&i.WorkspaceID,
		&i.JobID,
		&i.SessionID,
		&i.Status,
		&i.ArchiveReason,
		&i.UserReply,
		&i.ProcessedAt,
		&i.ProcessError,
		&i.ProcessAttempts,
		&i.ArchivedAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getInboxMessage = `-- name: GetInboxMessage :one
SELECT id, title, body, workspace_id, job_id, session_id, status, archive_reason, user_reply, processed_at, process_error, process_attempts, archived_at, deleted_at, created_at, updated_at
FROM inbox_messages
WHERE id = ?
  AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetInboxMessage(ctx context.Context, id string) (InboxMessage, error) {
	row := q.db.QueryRowContext(ctx, getInboxMessage, id)
	var i InboxMessage
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Body,
		&i.WorkspaceID,
		&i.JobID,
		&i.SessionID,
		&i.Status,
		&i.ArchiveReason,
		&i.UserReply,
		&i.ProcessedAt,
		&i.ProcessError,
		&i.ProcessAttempts,
		&i.ArchivedAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listInboxMessages = `-- name: ListInboxMessages :many
SELECT id, title, body, workspace_id, job_id, session_id, status, archive_reason, user_reply, processed_at, process_error, process_attempts, archived_at, deleted_at, created_at, updated_at
FROM inbox_messages
WHERE deleted_at IS NULL
  AND (
    ?1 IS NULL
    OR status = ?1
  )
ORDER BY created_at DESC
`

func (q *Queries) ListInboxMessages(ctx context.Context, status interface{}) ([]InboxMessage, error) {
	rows, err := q.db.QueryContext(ctx, listInboxMessages, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InboxMessage{}
	for rows.Next() {
		var i InboxMessage
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Body,
			&i.WorkspaceID,
			&i.JobID,
			&i.SessionID,
			&i.Status,
			&i.ArchiveReason,
			&i.UserReply,
			&i.ProcessedAt,
			&i.ProcessError,
			&i.ProcessAttempts,
			&i.ArchivedAt,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInboxMessagesPendingProcess = `-- name: ListInboxMessagesPendingProcess :many
SELECT id, title, body, workspace_id, job_id, session_id, status, archive_reason, user_reply, processed_at, process_error, process_attempts, archived_at, deleted_at, created_at, updated_at
FROM inbox_messages
WHERE status = 'archived'
  AND archive_reason = 'replied'
  AND processed_at IS NULL
  AND deleted_at IS NULL
  AND process_attempts < ?
ORDER BY archived_at ASC
LIMIT ?
`

type ListInboxMessagesPendingProcessParams struct {
	ProcessAttempts int64 `json:"process_attempts"`
	Limit           int64 `json:"limit"`
}

func (q *Queries) ListInboxMessagesPendingProcess(ctx context.Context, arg ListInboxMessagesPendingProcessParams) ([]InboxMessage, error) {
	rows, err := q.db.QueryContext(ctx, listInboxMessagesPendingProcess, arg.ProcessAttempts, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InboxMessage{}
	for rows.Next() {
		var i InboxMessage
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Body,
			&i.WorkspaceID,
			&i.JobID,
			&i.SessionID,
			&i.Status,
			&i.ArchiveReason,
			&i.UserReply,
			&i.ProcessedAt,
			&i.ProcessError,
			&i.ProcessAttempts,
			&i.ArchivedAt,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markInboxMessageProcessed = `-- name: MarkInboxMessageProcessed :one
UPDATE inbox_messages
SET
    processed_at = ?,
    process_error = ?,
    updated_at = ?
WHERE id = ?
RETURNING id, title, body, workspace_id, job_id, session_id, status, archive_reason, user_reply, processed_at, process_error, process_attempts, archived_at, deleted_at, created_at, updated_at
`

type MarkInboxMessageProcessedParams struct {
	ProcessedAt  sql.NullInt64  `json:"processed_at"`
	ProcessError sql.NullString `json:"process_error"`
	UpdatedAt    int64          `json:"updated_at"`
	ID           string         `json:"id"`
}

func (q *Queries) MarkInboxMessageProcessed(ctx context.Context, arg MarkInboxMessageProcessedParams) (InboxMessage, error) {
	row := q.db.QueryRowContext(ctx, markInboxMessageProcessed,
		arg.ProcessedAt,
		arg.ProcessError,
		arg.UpdatedAt,
		arg.ID,
	)
	var i InboxMessage
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Body,
		&i.WorkspaceID,
		&i.JobID,
		&i.SessionID,
		&i.Status,
		&i.ArchiveReason,
		&i.UserReply,
		&i.ProcessedAt,
		&i.ProcessError,
		&i.ProcessAttempts,
		&i.ArchivedAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const replyInboxMessage = `-- name: ReplyInboxMessage :one
UPDATE inbox_messages
SET
    status = 'archived',
    archive_reason = 'replied',
    user_reply = ?,
    archived_at = ?,
    updated_at = ?
WHERE id = ?
  AND status = 'open'
  AND deleted_at IS NULL
RETURNING id, title, body, workspace_id, job_id, session_id, status, archive_reason, user_reply, processed_at, process_error, process_attempts, archived_at, deleted_at, created_at, updated_at
`

type ReplyInboxMessageParams struct {
	UserReply  sql.NullString `json:"user_reply"`
	ArchivedAt sql.NullInt64  `json:"archived_at"`
	UpdatedAt  int64          `json:"updated_at"`
	ID         string         `json:"id"`
}

func (q *Queries) ReplyInboxMessage(ctx context.Context, arg ReplyInboxMessageParams) (InboxMessage, error) {
	row := q.db.QueryRowContext(ctx, replyInboxMessage,
		arg.UserReply,
		arg.ArchivedAt,
		arg.UpdatedAt,
		arg.ID,
	)
	var i InboxMessage
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Body,
		&i.WorkspaceID,
		&i.JobID,
		&i.SessionID,
		&i.Status,
		&i.ArchiveReason,
		&i.UserReply,
		&i.ProcessedAt,
		&i.ProcessError,
		&i.ProcessAttempts,
		&i.ArchivedAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
