// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: jobs.sql

package db

import (
	"context"
	"database/sql"
)

const archiveJob = `-- name: ArchiveJob :execrows
UPDATE jobs
SET
    archived_at = ?,
    lease_expires_at = NULL,
    updated_at = ?
WHERE id = ?
  AND status = 'done'
  AND deleted_at IS NULL
  AND archived_at IS NULL
`

type ArchiveJobParams struct {
	ArchivedAt sql.NullInt64 `json:"archived_at"`
	UpdatedAt  int64         `json:"updated_at"`
	ID         string        `json:"id"`
}

func (q *Queries) ArchiveJob(ctx context.Context, arg ArchiveJobParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, archiveJob, arg.ArchivedAt, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const claimJob = `-- name: ClaimJob :execrows
UPDATE jobs
SET
    status = 'ongoing',
    assigned_session_id = ?,
    lease_expires_at = ?,
    updated_at = ?
WHERE id = ?
  AND status = 'todo'
  AND deleted_at IS NULL
  AND archived_at IS NULL
  AND (next_retry_at IS NULL OR next_retry_at <= ?)
  AND assigned_session_id IS NULL
`

type ClaimJobParams struct {
	AssignedSessionID sql.NullString `json:"assigned_session_id"`
	LeaseExpiresAt    sql.NullInt64  `json:"lease_expires_at"`
	UpdatedAt         int64          `json:"updated_at"`
	ID                string         `json:"id"`
	NextRetryAt       sql.NullInt64  `json:"next_retry_at"`
}

func (q *Queries) ClaimJob(ctx context.Context, arg ClaimJobParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, claimJob,
		arg.AssignedSessionID,
		arg.LeaseExpiresAt,
		arg.UpdatedAt,
		arg.ID,
		arg.NextRetryAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const completeJob = `-- name: CompleteJob :execrows
UPDATE jobs
SET
    status = 'done',
    lease_expires_at = NULL,
    failure_count = 0,
    next_retry_at = NULL,
    last_failure_reason = NULL,
    updated_at = ?
WHERE id = ?
  AND status = 'ongoing'
  AND deleted_at IS NULL
  AND archived_at IS NULL
`

type CompleteJobParams struct {
	UpdatedAt int64  `json:"updated_at"`
	ID        string `json:"id"`
}

func (q *Queries) CompleteJob(ctx context.Context, arg CompleteJobParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, completeJob, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getJob = `-- name: GetJob :one
SELECT id, description, definition_of_done, progress, status, workspace_path, assigned_session_id, lease_expires_at, created_by, source_session_id, source_platform, source_channel_id, archived_at, failure_count, next_retry_at, last_failure_reason, deleted_at, scheduled_job_id, created_at, updated_at
FROM jobs
WHERE id = ?
`

func (q *Queries) GetJob(ctx context.Context, id string) (Job, error) {
	row := q.db.QueryRowContext(ctx, getJob, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Description,
		&i.DefinitionOfDone,
		&i.Progress,
		&i.Status,
		&i.WorkspacePath,
		&i.AssignedSessionID,
		&i.LeaseExpiresAt,
		&i.CreatedBy,
		&i.SourceSessionID,
		&i.SourcePlatform,
		&i.SourceChannelID,
		&i.ArchivedAt,
		&i.FailureCount,
		&i.NextRetryAt,
		&i.LastFailureReason,
		&i.DeletedAt,
		&i.ScheduledJobID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getJobByAssignedSession = `-- name: GetJobByAssignedSession :one
SELECT id, description, definition_of_done, progress, status, workspace_path, assigned_session_id, lease_expires_at, created_by, source_session_id, source_platform, source_channel_id, archived_at, failure_count, next_retry_at, last_failure_reason, deleted_at, scheduled_job_id, created_at, updated_at
FROM jobs
WHERE assigned_session_id = ?
  AND status = 'ongoing'
  AND deleted_at IS NULL
  AND archived_at IS NULL
LIMIT 1
`

func (q *Queries) GetJobByAssignedSession(ctx context.Context, assignedSessionID sql.NullString) (Job, error) {
	row := q.db.QueryRowContext(ctx, getJobByAssignedSession, assignedSessionID)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Description,
		&i.DefinitionOfDone,
		&i.Progress,
		&i.Status,
		&i.WorkspacePath,
		&i.AssignedSessionID,
		&i.LeaseExpiresAt,
		&i.CreatedBy,
		&i.SourceSessionID,
		&i.SourcePlatform,
		&i.SourceChannelID,
		&i.ArchivedAt,
		&i.FailureCount,
		&i.NextRetryAt,
		&i.LastFailureReason,
		&i.DeletedAt,
		&i.ScheduledJobID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const hardDeleteJob = `-- name: HardDeleteJob :exec
DELETE FROM jobs
WHERE id = ?
`

func (q *Queries) HardDeleteJob(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, hardDeleteJob, id)
	return err
}

const hasOpenJobForScheduledJob = `-- name: HasOpenJobForScheduledJob :one
SELECT EXISTS (
    SELECT 1
    FROM jobs
    WHERE scheduled_job_id = ?
      AND status IN ('todo', 'ongoing', 'blocked')
      AND deleted_at IS NULL
) AS has_open_job
`

func (q *Queries) HasOpenJobForScheduledJob(ctx context.Context, scheduledJobID sql.NullString) (bool, error) {
	row := q.db.QueryRowContext(ctx, hasOpenJobForScheduledJob, scheduledJobID)
	var has_open_job bool
	err := row.Scan(&has_open_job)
	return has_open_job, err
}

const heartbeatJob = `-- name: HeartbeatJob :execrows
UPDATE jobs
SET
    lease_expires_at = ?,
    updated_at = ?
WHERE id = ?
  AND status = 'ongoing'
  AND assigned_session_id = ?
  AND deleted_at IS NULL
  AND archived_at IS NULL
`

type HeartbeatJobParams struct {
	LeaseExpiresAt    sql.NullInt64  `json:"lease_expires_at"`
	UpdatedAt         int64          `json:"updated_at"`
	ID                string         `json:"id"`
	AssignedSessionID sql.NullString `json:"assigned_session_id"`
}

func (q *Queries) HeartbeatJob(ctx context.Context, arg HeartbeatJobParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, heartbeatJob,
		arg.LeaseExpiresAt,
		arg.UpdatedAt,
		arg.ID,
		arg.AssignedSessionID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const insertJob = `-- name: InsertJob :exec
INSERT INTO jobs (
    id,
    description,
    definition_of_done,
    progress,
    status,
    workspace_path,
    assigned_session_id,
    lease_expires_at,
    created_by,
    source_session_id,
    source_platform,
    source_channel_id,
    archived_at,
    failure_count,
    next_retry_at,
    last_failure_reason,
    deleted_at,
    scheduled_job_id,
    created_at,
    updated_at
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
)
`

type InsertJobParams struct {
	ID                string         `json:"id"`
	Description       string         `json:"description"`
	DefinitionOfDone  string         `json:"definition_of_done"`
	Progress          string         `json:"progress"`
	Status            string         `json:"status"`
	WorkspacePath     sql.NullString `json:"workspace_path"`
	AssignedSessionID sql.NullString `json:"assigned_session_id"`
	LeaseExpiresAt    sql.NullInt64  `json:"lease_expires_at"`
	CreatedBy         string         `json:"created_by"`
	SourceSessionID   sql.NullString `json:"source_session_id"`
	SourcePlatform    string         `json:"source_platform"`
	SourceChannelID   sql.NullString `json:"source_channel_id"`
	ArchivedAt        sql.NullInt64  `json:"archived_at"`
	FailureCount      int64          `json:"failure_count"`
	NextRetryAt       sql.NullInt64  `json:"next_retry_at"`
	LastFailureReason sql.NullString `json:"last_failure_reason"`
	DeletedAt         sql.NullInt64  `json:"deleted_at"`
	ScheduledJobID    sql.NullString `json:"scheduled_job_id"`
	CreatedAt         int64          `json:"created_at"`
	UpdatedAt         int64          `json:"updated_at"`
}

func (q *Queries) InsertJob(ctx context.Context, arg InsertJobParams) error {
	_, err := q.db.ExecContext(ctx, insertJob,
		arg.ID,
		arg.Description,
		arg.DefinitionOfDone,
		arg.Progress,
		arg.Status,
		arg.WorkspacePath,
		arg.AssignedSessionID,
		arg.LeaseExpiresAt,
		arg.CreatedBy,
		arg.SourceSessionID,
		arg.SourcePlatform,
		arg.SourceChannelID,
		arg.ArchivedAt,
		arg.FailureCount,
		arg.NextRetryAt,
		arg.LastFailureReason,
		arg.DeletedAt,
		arg.ScheduledJobID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const insertJobEvent = `-- name: InsertJobEvent :exec
INSERT INTO job_events (
    id,
    job_id,
    action,
    detail,
    actor_session_id,
    created_at
) VALUES (?, ?, ?, ?, ?, ?)
`

type InsertJobEventParams struct {
	ID             string         `json:"id"`
	JobID          string         `json:"job_id"`
	Action         string         `json:"action"`
	Detail         string         `json:"detail"`
	ActorSessionID sql.NullString `json:"actor_session_id"`
	CreatedAt      int64          `json:"created_at"`
}

func (q *Queries) InsertJobEvent(ctx context.Context, arg InsertJobEventParams) error {
	_, err := q.db.ExecContext(ctx, insertJobEvent,
		arg.ID,
		arg.JobID,
		arg.Action,
		arg.Detail,
		arg.ActorSessionID,
		arg.CreatedAt,
	)
	return err
}

const listArchivedJobsBefore = `-- name: ListArchivedJobsBefore :many
SELECT id
FROM jobs
WHERE deleted_at IS NULL
  AND archived_at IS NOT NULL
  AND archived_at < ?
`

func (q *Queries) ListArchivedJobsBefore(ctx context.Context, archivedAt sql.NullInt64) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listArchivedJobsBefore, archivedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeletedJobsBefore = `-- name: ListDeletedJobsBefore :many
SELECT id
FROM jobs
WHERE deleted_at IS NOT NULL
  AND deleted_at < ?
`

func (q *Queries) ListDeletedJobsBefore(ctx context.Context, deletedAt sql.NullInt64) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listDeletedJobsBefore, deletedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDoneJobsBefore = `-- name: ListDoneJobsBefore :many
SELECT id
FROM jobs
WHERE deleted_at IS NULL
  AND archived_at IS NULL
  AND status = 'done'
  AND updated_at < ?
`

func (q *Queries) ListDoneJobsBefore(ctx context.Context, updatedAt int64) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listDoneJobsBefore, updatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobEvents = `-- name: ListJobEvents :many
SELECT id, job_id, "action", detail, actor_session_id, created_at
FROM job_events
WHERE job_id = ?
ORDER BY created_at ASC
`

func (q *Queries) ListJobEvents(ctx context.Context, jobID string) ([]JobEvent, error) {
	rows, err := q.db.QueryContext(ctx, listJobEvents, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []JobEvent{}
	for rows.Next() {
		var i JobEvent
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.Action,
			&i.Detail,
			&i.ActorSessionID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobs = `-- name: ListJobs :many
SELECT id, description, definition_of_done, progress, status, workspace_path, assigned_session_id, lease_expires_at, created_by, source_session_id, source_platform, source_channel_id, archived_at, failure_count, next_retry_at, last_failure_reason, deleted_at, scheduled_job_id, created_at, updated_at
FROM jobs
WHERE (?1 = 1 OR deleted_at IS NULL)
  AND (?2 = 1 OR archived_at IS NULL)
  AND (?3 IS NULL OR status = ?3)
ORDER BY updated_at ASC
`

type ListJobsParams struct {
	IncludeDeleted  interface{} `json:"include_deleted"`
	IncludeArchived interface{} `json:"include_archived"`
	Status          interface{} `json:"status"`
}

func (q *Queries) ListJobs(ctx context.Context, arg ListJobsParams) ([]Job, error) {
	rows, err := q.db.QueryContext(ctx, listJobs, arg.IncludeDeleted, arg.IncludeArchived, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Job{}
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.Description,
			&i.DefinitionOfDone,
			&i.Progress,
			&i.Status,
			&i.WorkspacePath,
			&i.AssignedSessionID,
			&i.LeaseExpiresAt,
			&i.CreatedBy,
			&i.SourceSessionID,
			&i.SourcePlatform,
			&i.SourceChannelID,
			&i.ArchivedAt,
			&i.FailureCount,
			&i.NextRetryAt,
			&i.LastFailureReason,
			&i.DeletedAt,
			&i.ScheduledJobID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOngoingJobs = `-- name: ListOngoingJobs :many
SELECT id, description, definition_of_done, progress, status, workspace_path, assigned_session_id, lease_expires_at, created_by, source_session_id, source_platform, source_channel_id, archived_at, failure_count, next_retry_at, last_failure_reason, deleted_at, scheduled_job_id, created_at, updated_at
FROM jobs
WHERE deleted_at IS NULL
  AND archived_at IS NULL
  AND status = 'ongoing'
`

func (q *Queries) ListOngoingJobs(ctx context.Context) ([]Job, error) {
	rows, err := q.db.QueryContext(ctx, listOngoingJobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Job{}
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.Description,
			&i.DefinitionOfDone,
			&i.Progress,
			&i.Status,
			&i.WorkspacePath,
			&i.AssignedSessionID,
			&i.LeaseExpiresAt,
			&i.CreatedBy,
			&i.SourceSessionID,
			&i.SourcePlatform,
			&i.SourceChannelID,
			&i.ArchivedAt,
			&i.FailureCount,
			&i.NextRetryAt,
			&i.LastFailureReason,
			&i.DeletedAt,
			&i.ScheduledJobID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReadyJobs = `-- name: ListReadyJobs :many
SELECT id, description, definition_of_done, progress, status, workspace_path, assigned_session_id, lease_expires_at, created_by, source_session_id, source_platform, source_channel_id, archived_at, failure_count, next_retry_at, last_failure_reason, deleted_at, scheduled_job_id, created_at, updated_at
FROM jobs
WHERE deleted_at IS NULL
  AND archived_at IS NULL
  AND status = 'todo'
  AND (next_retry_at IS NULL OR next_retry_at <= ?)
ORDER BY updated_at ASC
`

func (q *Queries) ListReadyJobs(ctx context.Context, nextRetryAt sql.NullInt64) ([]Job, error) {
	rows, err := q.db.QueryContext(ctx, listReadyJobs, nextRetryAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Job{}
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.Description,
			&i.DefinitionOfDone,
			&i.Progress,
			&i.Status,
			&i.WorkspacePath,
			&i.AssignedSessionID,
			&i.LeaseExpiresAt,
			&i.CreatedBy,
			&i.SourceSessionID,
			&i.SourcePlatform,
			&i.SourceChannelID,
			&i.ArchivedAt,
			&i.FailureCount,
			&i.NextRetryAt,
			&i.LastFailureReason,
			&i.DeletedAt,
			&i.ScheduledJobID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordJobFailure = `-- name: RecordJobFailure :execrows
UPDATE jobs
SET
    failure_count = failure_count + 1,
    next_retry_at = ?,
    last_failure_reason = ?,
    status = ?,
    assigned_session_id = NULL,
    lease_expires_at = NULL,
    updated_at = ?
WHERE id = ?
  AND status = 'ongoing'
  AND deleted_at IS NULL
  AND archived_at IS NULL
`

type RecordJobFailureParams struct {
	NextRetryAt       sql.NullInt64  `json:"next_retry_at"`
	LastFailureReason sql.NullString `json:"last_failure_reason"`
	Status            string         `json:"status"`
	UpdatedAt         int64          `json:"updated_at"`
	ID                string         `json:"id"`
}

func (q *Queries) RecordJobFailure(ctx context.Context, arg RecordJobFailureParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, recordJobFailure,
		arg.NextRetryAt,
		arg.LastFailureReason,
		arg.Status,
		arg.UpdatedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const releaseJob = `-- name: ReleaseJob :execrows
UPDATE jobs
SET
    status = 'todo',
    assigned_session_id = NULL,
    lease_expires_at = NULL,
    updated_at = ?
WHERE id = ?
  AND status = 'ongoing'
  AND deleted_at IS NULL
  AND archived_at IS NULL
`

type ReleaseJobParams struct {
	UpdatedAt int64  `json:"updated_at"`
	ID        string `json:"id"`
}

func (q *Queries) ReleaseJob(ctx context.Context, arg ReleaseJobParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, releaseJob, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const resetJobFailures = `-- name: ResetJobFailures :execrows
UPDATE jobs
SET
    failure_count = 0,
    next_retry_at = NULL,
    last_failure_reason = NULL,
    status = 'todo',
    assigned_session_id = NULL,
    lease_expires_at = NULL,
    updated_at = ?
WHERE id = ?
  AND status = 'blocked'
  AND deleted_at IS NULL
  AND archived_at IS NULL
`

type ResetJobFailuresParams struct {
	UpdatedAt int64  `json:"updated_at"`
	ID        string `json:"id"`
}

func (q *Queries) ResetJobFailures(ctx context.Context, arg ResetJobFailuresParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, resetJobFailures, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const softDeleteJob = `-- name: SoftDeleteJob :execrows
UPDATE jobs
SET
    deleted_at = ?,
    archived_at = NULL,
    failure_count = 0,
    next_retry_at = NULL,
    last_failure_reason = NULL,
    assigned_session_id = NULL,
    lease_expires_at = NULL,
    status = CASE WHEN status IN ('ongoing', 'blocked') THEN 'todo' ELSE status END,
    updated_at = ?
WHERE id = ?
  AND deleted_at IS NULL
`

type SoftDeleteJobParams struct {
	DeletedAt sql.NullInt64 `json:"deleted_at"`
	UpdatedAt int64         `json:"updated_at"`
	ID        string        `json:"id"`
}

func (q *Queries) SoftDeleteJob(ctx context.Context, arg SoftDeleteJobParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, softDeleteJob, arg.DeletedAt, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const unarchiveJob = `-- name: UnarchiveJob :execrows
UPDATE jobs
SET
    archived_at = NULL,
    updated_at = ?
WHERE id = ?
  AND deleted_at IS NULL
  AND archived_at IS NOT NULL
`

type UnarchiveJobParams struct {
	UpdatedAt int64  `json:"updated_at"`
	ID        string `json:"id"`
}

func (q *Queries) UnarchiveJob(ctx context.Context, arg UnarchiveJobParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, unarchiveJob, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateJobProgress = `-- name: UpdateJobProgress :execrows
UPDATE jobs
SET
    progress = ?,
    updated_at = ?
WHERE id = ?
  AND status = 'ongoing'
  AND deleted_at IS NULL
  AND archived_at IS NULL
`

type UpdateJobProgressParams struct {
	Progress  string `json:"progress"`
	UpdatedAt int64  `json:"updated_at"`
	ID        string `json:"id"`
}

func (q *Queries) UpdateJobProgress(ctx context.Context, arg UpdateJobProgressParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateJobProgress, arg.Progress, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateJobTodoFields = `-- name: UpdateJobTodoFields :execrows
UPDATE jobs
SET
    description = ?,
    definition_of_done = ?,
    workspace_path = ?,
    updated_at = ?
WHERE id = ?
  AND status = 'todo'
  AND deleted_at IS NULL
  AND archived_at IS NULL
`

type UpdateJobTodoFieldsParams struct {
	Description      string         `json:"description"`
	DefinitionOfDone string         `json:"definition_of_done"`
	WorkspacePath    sql.NullString `json:"workspace_path"`
	UpdatedAt        int64          `json:"updated_at"`
	ID               string         `json:"id"`
}

func (q *Queries) UpdateJobTodoFields(ctx context.Context, arg UpdateJobTodoFieldsParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateJobTodoFields,
		arg.Description,
		arg.DefinitionOfDone,
		arg.WorkspacePath,
		arg.UpdatedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
