// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
)

type GatewaySession struct {
	ID                 string `json:"id"`
	Platform           string `json:"platform"`
	PlatformUserID     string `json:"platform_user_id"`
	PlatformChannelID  string `json:"platform_channel_id"`
	ThreadID           string `json:"thread_id"`
	CometmindSessionID string `json:"cometmind_session_id"`
	WorkspaceID        string `json:"workspace_id"`
	LastActiveAt       int64  `json:"last_active_at"`
}

type InboxMessage struct {
	ID              string         `json:"id"`
	Title           string         `json:"title"`
	Body            string         `json:"body"`
	WorkspaceID     sql.NullString `json:"workspace_id"`
	JobID           sql.NullString `json:"job_id"`
	SessionID       sql.NullString `json:"session_id"`
	Status          string         `json:"status"`
	ArchiveReason   sql.NullString `json:"archive_reason"`
	UserReply       sql.NullString `json:"user_reply"`
	ProcessedAt     sql.NullInt64  `json:"processed_at"`
	ProcessError    sql.NullString `json:"process_error"`
	ProcessAttempts int64          `json:"process_attempts"`
	ArchivedAt      sql.NullInt64  `json:"archived_at"`
	DeletedAt       sql.NullInt64  `json:"deleted_at"`
	CreatedAt       int64          `json:"created_at"`
	UpdatedAt       int64          `json:"updated_at"`
}

type Job struct {
	ID                string         `json:"id"`
	Description       string         `json:"description"`
	DefinitionOfDone  string         `json:"definition_of_done"`
	Progress          string         `json:"progress"`
	Status            string         `json:"status"`
	WorkspacePath     sql.NullString `json:"workspace_path"`
	AssignedSessionID sql.NullString `json:"assigned_session_id"`
	LeaseExpiresAt    sql.NullInt64  `json:"lease_expires_at"`
	CreatedBy         string         `json:"created_by"`
	SourceSessionID   sql.NullString `json:"source_session_id"`
	SourcePlatform    string         `json:"source_platform"`
	SourceChannelID   sql.NullString `json:"source_channel_id"`
	ArchivedAt        sql.NullInt64  `json:"archived_at"`
	FailureCount      int64          `json:"failure_count"`
	NextRetryAt       sql.NullInt64  `json:"next_retry_at"`
	LastFailureReason sql.NullString `json:"last_failure_reason"`
	DeletedAt         sql.NullInt64  `json:"deleted_at"`
	ScheduledJobID    sql.NullString `json:"scheduled_job_id"`
	CreatedAt         int64          `json:"created_at"`
	UpdatedAt         int64          `json:"updated_at"`
}

type JobEvent struct {
	ID             string         `json:"id"`
	JobID          string         `json:"job_id"`
	Action         string         `json:"action"`
	Detail         string         `json:"detail"`
	ActorSessionID sql.NullString `json:"actor_session_id"`
	CreatedAt      int64          `json:"created_at"`
}

type MemoriesFt struct {
	MemoryID string `json:"memory_id"`
	Content  string `json:"content"`
}

type Memory struct {
	ID                 string         `json:"id"`
	Scope              string         `json:"scope"`
	Kind               string         `json:"kind"`
	PreferenceCategory string         `json:"preference_category"`
	Content            string         `json:"content"`
	Embedding          []byte         `json:"embedding"`
	EmbeddingModel     sql.NullString `json:"embedding_model"`
	Source             string         `json:"source"`
	BaseWeight         float64        `json:"base_weight"`
	AccessCount        int64          `json:"access_count"`
	Pinned             int64          `json:"pinned"`
	SourceSessionID    sql.NullString `json:"source_session_id"`
	SupersededBy       sql.NullString `json:"superseded_by"`
	Archived           int64          `json:"archived"`
	ArchivedReason     sql.NullString `json:"archived_reason"`
	LastAccessedAt     sql.NullInt64  `json:"last_accessed_at"`
	CreatedAt          int64          `json:"created_at"`
	UpdatedAt          int64          `json:"updated_at"`
}

type MemoryEvent struct {
	ID        string         `json:"id"`
	MemoryID  sql.NullString `json:"memory_id"`
	Action    string         `json:"action"`
	Detail    string         `json:"detail"`
	CreatedAt int64          `json:"created_at"`
}

type Message struct {
	ID               string `json:"id"`
	SessionID        string `json:"session_id"`
	Role             string `json:"role"`
	Content          string `json:"content"`
	ReasoningContent string `json:"reasoning_content"`
	InjectedMemories string `json:"injected_memories"`
	TokenCount       int64  `json:"token_count"`
	CreatedAt        int64  `json:"created_at"`
}

type ScheduledJob struct {
	ID               string         `json:"id"`
	Description      string         `json:"description"`
	DefinitionOfDone string         `json:"definition_of_done"`
	WorkspacePath    sql.NullString `json:"workspace_path"`
	CreatedBy        string         `json:"created_by"`
	SourceSessionID  sql.NullString `json:"source_session_id"`
	SourcePlatform   string         `json:"source_platform"`
	SourceChannelID  sql.NullString `json:"source_channel_id"`
	CronExpr         sql.NullString `json:"cron_expr"`
	RunAt            sql.NullInt64  `json:"run_at"`
	NextRunAt        int64          `json:"next_run_at"`
	LastRunAt        sql.NullInt64  `json:"last_run_at"`
	Enabled          int64          `json:"enabled"`
	CreatedAt        int64          `json:"created_at"`
	UpdatedAt        int64          `json:"updated_at"`
}

type Session struct {
	ID                      string         `json:"id"`
	WorkspaceID             string         `json:"workspace_id"`
	Title                   string         `json:"title"`
	ModelID                 string         `json:"model_id"`
	ProviderID              string         `json:"provider_id"`
	Status                  string         `json:"status"`
	Origin                  string         `json:"origin"`
	TokenUsage              string         `json:"token_usage"`
	ParentSessionID         sql.NullString `json:"parent_session_id"`
	Purpose                 string         `json:"purpose"`
	DelegationStatus        string         `json:"delegation_status"`
	OutputSummary           string         `json:"output_summary"`
	AcpSessionID            string         `json:"acp_session_id"`
	PendingQuestion         string         `json:"pending_question"`
	SubagentKind            string         `json:"subagent_kind"`
	Pinned                  int64          `json:"pinned"`
	ContextSummary          string         `json:"context_summary"`
	CompactedUntilMessageID sql.NullString `json:"compacted_until_message_id"`
	ContextSummaryUpdatedAt sql.NullString `json:"context_summary_updated_at"`
	CreatedAt               int64          `json:"created_at"`
	UpdatedAt               int64          `json:"updated_at"`
}

type ToolCall struct {
	ID         string        `json:"id"`
	MessageID  string        `json:"message_id"`
	ToolName   string        `json:"tool_name"`
	Arguments  string        `json:"arguments"`
	Result     string        `json:"result"`
	DurationMs int64         `json:"duration_ms"`
	ExitCode   sql.NullInt64 `json:"exit_code"`
	CreatedAt  int64         `json:"created_at"`
}

type Workspace struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	Path      string `json:"path"`
	CreatedAt int64  `json:"created_at"`
}
