// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: model_capability.sql

package db

import (
	"context"
)

const deleteExpiredModelCapabilityNegatives = `-- name: DeleteExpiredModelCapabilityNegatives :exec
DELETE FROM model_capability_negatives
WHERE expires_at <= ?
`

func (q *Queries) DeleteExpiredModelCapabilityNegatives(ctx context.Context, expiresAt int64) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredModelCapabilityNegatives, expiresAt)
	return err
}

const listActiveModelCapabilityNegatives = `-- name: ListActiveModelCapabilityNegatives :many
SELECT feature
FROM model_capability_negatives
WHERE provider_id = ?
  AND endpoint = ?
  AND model_id = ?
  AND expires_at > ?
`

type ListActiveModelCapabilityNegativesParams struct {
	ProviderID string `json:"provider_id"`
	Endpoint   string `json:"endpoint"`
	ModelID    string `json:"model_id"`
	ExpiresAt  int64  `json:"expires_at"`
}

func (q *Queries) ListActiveModelCapabilityNegatives(ctx context.Context, arg ListActiveModelCapabilityNegativesParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listActiveModelCapabilityNegatives,
		arg.ProviderID,
		arg.Endpoint,
		arg.ModelID,
		arg.ExpiresAt,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var feature string
		if err := rows.Scan(&feature); err != nil {
			return nil, err
		}
		items = append(items, feature)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertModelCapabilityNegative = `-- name: UpsertModelCapabilityNegative :exec
INSERT INTO model_capability_negatives (provider_id, endpoint, model_id, feature, expires_at)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT (provider_id, endpoint, model_id, feature)
DO UPDATE SET expires_at = excluded.expires_at
`

type UpsertModelCapabilityNegativeParams struct {
	ProviderID string `json:"provider_id"`
	Endpoint   string `json:"endpoint"`
	ModelID    string `json:"model_id"`
	Feature    string `json:"feature"`
	ExpiresAt  int64  `json:"expires_at"`
}

func (q *Queries) UpsertModelCapabilityNegative(ctx context.Context, arg UpsertModelCapabilityNegativeParams) error {
	_, err := q.db.ExecContext(ctx, upsertModelCapabilityNegative,
		arg.ProviderID,
		arg.Endpoint,
		arg.ModelID,
		arg.Feature,
		arg.ExpiresAt,
	)
	return err
}
