// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: scheduled_jobs.sql

package db

import (
	"context"
	"database/sql"
)

const advanceScheduledJob = `-- name: AdvanceScheduledJob :execrows
UPDATE scheduled_jobs
SET last_run_at = ?,
    next_run_at = ?,
    updated_at = ?
WHERE id = ? AND enabled = 1
`

type AdvanceScheduledJobParams struct {
	LastRunAt sql.NullInt64 `json:"last_run_at"`
	NextRunAt int64         `json:"next_run_at"`
	UpdatedAt int64         `json:"updated_at"`
	ID        string        `json:"id"`
}

func (q *Queries) AdvanceScheduledJob(ctx context.Context, arg AdvanceScheduledJobParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, advanceScheduledJob,
		arg.LastRunAt,
		arg.NextRunAt,
		arg.UpdatedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteScheduledJob = `-- name: DeleteScheduledJob :execrows
DELETE FROM scheduled_jobs WHERE id = ?
`

func (q *Queries) DeleteScheduledJob(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteScheduledJob, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getScheduledJob = `-- name: GetScheduledJob :one
SELECT id, description, definition_of_done, workspace_path, created_by, source_session_id, source_platform, source_channel_id, cron_expr, run_at, next_run_at, last_run_at, enabled, created_at, updated_at FROM scheduled_jobs WHERE id = ?
`

func (q *Queries) GetScheduledJob(ctx context.Context, id string) (ScheduledJob, error) {
	row := q.db.QueryRowContext(ctx, getScheduledJob, id)
	var i ScheduledJob
	err := row.Scan(
		&i.ID,
		&i.Description,
		&i.DefinitionOfDone,
		&i.WorkspacePath,
		&i.CreatedBy,
		&i.SourceSessionID,
		&i.SourcePlatform,
		&i.SourceChannelID,
		&i.CronExpr,
		&i.RunAt,
		&i.NextRunAt,
		&i.LastRunAt,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertScheduledJob = `-- name: InsertScheduledJob :exec
INSERT INTO scheduled_jobs (
  id,
  description,
  definition_of_done,
  workspace_path,
  created_by,
  source_session_id,
  source_platform,
  source_channel_id,
  cron_expr,
  run_at,
  next_run_at,
  last_run_at,
  enabled,
  created_at,
  updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertScheduledJobParams struct {
	ID               string         `json:"id"`
	Description      string         `json:"description"`
	DefinitionOfDone string         `json:"definition_of_done"`
	WorkspacePath    sql.NullString `json:"workspace_path"`
	CreatedBy        string         `json:"created_by"`
	SourceSessionID  sql.NullString `json:"source_session_id"`
	SourcePlatform   string         `json:"source_platform"`
	SourceChannelID  sql.NullString `json:"source_channel_id"`
	CronExpr         sql.NullString `json:"cron_expr"`
	RunAt            sql.NullInt64  `json:"run_at"`
	NextRunAt        int64          `json:"next_run_at"`
	LastRunAt        sql.NullInt64  `json:"last_run_at"`
	Enabled          int64          `json:"enabled"`
	CreatedAt        int64          `json:"created_at"`
	UpdatedAt        int64          `json:"updated_at"`
}

func (q *Queries) InsertScheduledJob(ctx context.Context, arg InsertScheduledJobParams) error {
	_, err := q.db.ExecContext(ctx, insertScheduledJob,
		arg.ID,
		arg.Description,
		arg.DefinitionOfDone,
		arg.WorkspacePath,
		arg.CreatedBy,
		arg.SourceSessionID,
		arg.SourcePlatform,
		arg.SourceChannelID,
		arg.CronExpr,
		arg.RunAt,
		arg.NextRunAt,
		arg.LastRunAt,
		arg.Enabled,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const listDueScheduledJobs = `-- name: ListDueScheduledJobs :many
SELECT id, description, definition_of_done, workspace_path, created_by, source_session_id, source_platform, source_channel_id, cron_expr, run_at, next_run_at, last_run_at, enabled, created_at, updated_at FROM scheduled_jobs
WHERE enabled = 1 AND next_run_at <= ?
ORDER BY next_run_at ASC
`

func (q *Queries) ListDueScheduledJobs(ctx context.Context, nextRunAt int64) ([]ScheduledJob, error) {
	rows, err := q.db.QueryContext(ctx, listDueScheduledJobs, nextRunAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScheduledJob{}
	for rows.Next() {
		var i ScheduledJob
		if err := rows.Scan(
			&i.ID,
			&i.Description,
			&i.DefinitionOfDone,
			&i.WorkspacePath,
			&i.CreatedBy,
			&i.SourceSessionID,
			&i.SourcePlatform,
			&i.SourceChannelID,
			&i.CronExpr,
			&i.RunAt,
			&i.NextRunAt,
			&i.LastRunAt,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScheduledJobs = `-- name: ListScheduledJobs :many
SELECT id, description, definition_of_done, workspace_path, created_by, source_session_id, source_platform, source_channel_id, cron_expr, run_at, next_run_at, last_run_at, enabled, created_at, updated_at FROM scheduled_jobs
ORDER BY enabled DESC, next_run_at ASC, updated_at DESC
`

func (q *Queries) ListScheduledJobs(ctx context.Context) ([]ScheduledJob, error) {
	rows, err := q.db.QueryContext(ctx, listScheduledJobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScheduledJob{}
	for rows.Next() {
		var i ScheduledJob
		if err := rows.Scan(
			&i.ID,
			&i.Description,
			&i.DefinitionOfDone,
			&i.WorkspacePath,
			&i.CreatedBy,
			&i.SourceSessionID,
			&i.SourcePlatform,
			&i.SourceChannelID,
			&i.CronExpr,
			&i.RunAt,
			&i.NextRunAt,
			&i.LastRunAt,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markScheduledJobFired = `-- name: MarkScheduledJobFired :execrows
UPDATE scheduled_jobs
SET last_run_at = ?,
    enabled = 0,
    updated_at = ?
WHERE id = ? AND enabled = 1
`

type MarkScheduledJobFiredParams struct {
	LastRunAt sql.NullInt64 `json:"last_run_at"`
	UpdatedAt int64         `json:"updated_at"`
	ID        string        `json:"id"`
}

func (q *Queries) MarkScheduledJobFired(ctx context.Context, arg MarkScheduledJobFiredParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markScheduledJobFired, arg.LastRunAt, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateScheduledJob = `-- name: UpdateScheduledJob :execrows
UPDATE scheduled_jobs
SET description = ?,
    definition_of_done = ?,
    workspace_path = ?,
    run_at = ?,
    next_run_at = ?,
    enabled = ?,
    updated_at = ?
WHERE id = ?
`

type UpdateScheduledJobParams struct {
	Description      string         `json:"description"`
	DefinitionOfDone string         `json:"definition_of_done"`
	WorkspacePath    sql.NullString `json:"workspace_path"`
	RunAt            sql.NullInt64  `json:"run_at"`
	NextRunAt        int64          `json:"next_run_at"`
	Enabled          int64          `json:"enabled"`
	UpdatedAt        int64          `json:"updated_at"`
	ID               string         `json:"id"`
}

func (q *Queries) UpdateScheduledJob(ctx context.Context, arg UpdateScheduledJobParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateScheduledJob,
		arg.Description,
		arg.DefinitionOfDone,
		arg.WorkspacePath,
		arg.RunAt,
		arg.NextRunAt,
		arg.Enabled,
		arg.UpdatedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
