// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: session_plans.sql

package db

import (
	"context"
	"database/sql"
)

const deletePlanForSession = `-- name: DeletePlanForSession :exec
DELETE FROM session_plans
WHERE session_id = ?
`

func (q *Queries) DeletePlanForSession(ctx context.Context, sessionID string) error {
	_, err := q.db.ExecContext(ctx, deletePlanForSession, sessionID)
	return err
}

const dismissPlanForSession = `-- name: DismissPlanForSession :execrows
UPDATE session_plans
SET dismissed_at = ?, updated_at = ?
WHERE session_id = ? AND dismissed_at IS NULL
`

type DismissPlanForSessionParams struct {
	DismissedAt sql.NullInt64 `json:"dismissed_at"`
	UpdatedAt   int64         `json:"updated_at"`
	SessionID   string        `json:"session_id"`
}

func (q *Queries) DismissPlanForSession(ctx context.Context, arg DismissPlanForSessionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, dismissPlanForSession, arg.DismissedAt, arg.UpdatedAt, arg.SessionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const insertPlanStep = `-- name: InsertPlanStep :exec
INSERT INTO session_plans (id, session_id, step_index, description, status, blocker_reason, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertPlanStepParams struct {
	ID            string `json:"id"`
	SessionID     string `json:"session_id"`
	StepIndex     int64  `json:"step_index"`
	Description   string `json:"description"`
	Status        string `json:"status"`
	BlockerReason string `json:"blocker_reason"`
	CreatedAt     int64  `json:"created_at"`
	UpdatedAt     int64  `json:"updated_at"`
}

func (q *Queries) InsertPlanStep(ctx context.Context, arg InsertPlanStepParams) error {
	_, err := q.db.ExecContext(ctx, insertPlanStep,
		arg.ID,
		arg.SessionID,
		arg.StepIndex,
		arg.Description,
		arg.Status,
		arg.BlockerReason,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const listPlanSteps = `-- name: ListPlanSteps :many
SELECT id, session_id, step_index, description, status, blocker_reason, dismissed_at, created_at, updated_at FROM session_plans
WHERE session_id = ?
ORDER BY step_index ASC
`

func (q *Queries) ListPlanSteps(ctx context.Context, sessionID string) ([]SessionPlan, error) {
	rows, err := q.db.QueryContext(ctx, listPlanSteps, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SessionPlan{}
	for rows.Next() {
		var i SessionPlan
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.StepIndex,
			&i.Description,
			&i.Status,
			&i.BlockerReason,
			&i.DismissedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePlanStep = `-- name: UpdatePlanStep :execrows
UPDATE session_plans
SET status = ?, blocker_reason = ?, updated_at = ?
WHERE session_id = ? AND step_index = ?
`

type UpdatePlanStepParams struct {
	Status        string `json:"status"`
	BlockerReason string `json:"blocker_reason"`
	UpdatedAt     int64  `json:"updated_at"`
	SessionID     string `json:"session_id"`
	StepIndex     int64  `json:"step_index"`
}

func (q *Queries) UpdatePlanStep(ctx context.Context, arg UpdatePlanStepParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updatePlanStep,
		arg.Status,
		arg.BlockerReason,
		arg.UpdatedAt,
		arg.SessionID,
		arg.StepIndex,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
