// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: session_media.sql

package db

import (
	"context"
	"database/sql"
)

const createSessionMedia = `-- name: CreateSessionMedia :one
INSERT INTO session_media (
    id,
    session_id,
    storage_session_id,
    workspace_id,
    kind,
    media_type,
    alt,
    prompt,
    model,
    provider_id,
    source,
    source_media_id,
    status,
    byte_size,
    duration_ms
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, session_id, storage_session_id, workspace_id, kind, media_type, alt, prompt, model, provider_id, source, source_media_id, status, byte_size, duration_ms, detached_at, created_at
`

type CreateSessionMediaParams struct {
	ID               string         `json:"id"`
	SessionID        sql.NullString `json:"session_id"`
	StorageSessionID string         `json:"storage_session_id"`
	WorkspaceID      sql.NullString `json:"workspace_id"`
	Kind             string         `json:"kind"`
	MediaType        string         `json:"media_type"`
	Alt              string         `json:"alt"`
	Prompt           string         `json:"prompt"`
	Model            string         `json:"model"`
	ProviderID       string         `json:"provider_id"`
	Source           string         `json:"source"`
	SourceMediaID    string         `json:"source_media_id"`
	Status           string         `json:"status"`
	ByteSize         int64          `json:"byte_size"`
	DurationMs       sql.NullInt64  `json:"duration_ms"`
}

func (q *Queries) CreateSessionMedia(ctx context.Context, arg CreateSessionMediaParams) (SessionMedia, error) {
	row := q.db.QueryRowContext(ctx, createSessionMedia,
		arg.ID,
		arg.SessionID,
		arg.StorageSessionID,
		arg.WorkspaceID,
		arg.Kind,
		arg.MediaType,
		arg.Alt,
		arg.Prompt,
		arg.Model,
		arg.ProviderID,
		arg.Source,
		arg.SourceMediaID,
		arg.Status,
		arg.ByteSize,
		arg.DurationMs,
	)
	var i SessionMedia
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.StorageSessionID,
		&i.WorkspaceID,
		&i.Kind,
		&i.MediaType,
		&i.Alt,
		&i.Prompt,
		&i.Model,
		&i.ProviderID,
		&i.Source,
		&i.SourceMediaID,
		&i.Status,
		&i.ByteSize,
		&i.DurationMs,
		&i.DetachedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getReadySessionMedia = `-- name: GetReadySessionMedia :one
SELECT id, session_id, storage_session_id, workspace_id, kind, media_type, alt, prompt, model, provider_id, source, source_media_id, status, byte_size, duration_ms, detached_at, created_at
FROM session_media
WHERE id = ?
  AND session_id = ?
  AND status = 'ready'
LIMIT 1
`

type GetReadySessionMediaParams struct {
	ID        string         `json:"id"`
	SessionID sql.NullString `json:"session_id"`
}

func (q *Queries) GetReadySessionMedia(ctx context.Context, arg GetReadySessionMediaParams) (SessionMedia, error) {
	row := q.db.QueryRowContext(ctx, getReadySessionMedia, arg.ID, arg.SessionID)
	var i SessionMedia
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.StorageSessionID,
		&i.WorkspaceID,
		&i.Kind,
		&i.MediaType,
		&i.Alt,
		&i.Prompt,
		&i.Model,
		&i.ProviderID,
		&i.Source,
		&i.SourceMediaID,
		&i.Status,
		&i.ByteSize,
		&i.DurationMs,
		&i.DetachedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getSessionMedia = `-- name: GetSessionMedia :one
SELECT id, session_id, storage_session_id, workspace_id, kind, media_type, alt, prompt, model, provider_id, source, source_media_id, status, byte_size, duration_ms, detached_at, created_at
FROM session_media
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetSessionMedia(ctx context.Context, id string) (SessionMedia, error) {
	row := q.db.QueryRowContext(ctx, getSessionMedia, id)
	var i SessionMedia
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.StorageSessionID,
		&i.WorkspaceID,
		&i.Kind,
		&i.MediaType,
		&i.Alt,
		&i.Prompt,
		&i.Model,
		&i.ProviderID,
		&i.Source,
		&i.SourceMediaID,
		&i.Status,
		&i.ByteSize,
		&i.DurationMs,
		&i.DetachedAt,
		&i.CreatedAt,
	)
	return i, err
}

const initializeDetachedSessionMedia = `-- name: InitializeDetachedSessionMedia :exec
UPDATE session_media
SET detached_at = ?
WHERE session_id IS NULL
  AND status = 'ready'
  AND detached_at = 0
`

func (q *Queries) InitializeDetachedSessionMedia(ctx context.Context, detachedAt int64) error {
	_, err := q.db.ExecContext(ctx, initializeDetachedSessionMedia, detachedAt)
	return err
}

const listExpiredDetachedSessionMediaIDs = `-- name: ListExpiredDetachedSessionMediaIDs :many
SELECT id
FROM session_media
WHERE session_id IS NULL
  AND status = 'ready'
  AND detached_at > 0
  AND detached_at <= ?
ORDER BY detached_at ASC
`

func (q *Queries) ListExpiredDetachedSessionMediaIDs(ctx context.Context, detachedAt int64) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listExpiredDetachedSessionMediaIDs, detachedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionMedia = `-- name: ListSessionMedia :many
SELECT id, session_id, storage_session_id, workspace_id, kind, media_type, alt, prompt, model, provider_id, source, source_media_id, status, byte_size, duration_ms, detached_at, created_at
FROM session_media
WHERE status = 'ready'
  AND (
    ?1 IS NULL
    OR workspace_id = ?1
  )
  AND (
    ?2 IS NULL
    OR session_id = ?2
  )
  AND (
    ?3 IS NULL
    OR kind = ?3
  )
ORDER BY created_at DESC
`

type ListSessionMediaParams struct {
	WorkspaceID interface{} `json:"workspace_id"`
	SessionID   interface{} `json:"session_id"`
	Kind        interface{} `json:"kind"`
}

func (q *Queries) ListSessionMedia(ctx context.Context, arg ListSessionMediaParams) ([]SessionMedia, error) {
	rows, err := q.db.QueryContext(ctx, listSessionMedia, arg.WorkspaceID, arg.SessionID, arg.Kind)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SessionMedia{}
	for rows.Next() {
		var i SessionMedia
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.StorageSessionID,
			&i.WorkspaceID,
			&i.Kind,
			&i.MediaType,
			&i.Alt,
			&i.Prompt,
			&i.Model,
			&i.ProviderID,
			&i.Source,
			&i.SourceMediaID,
			&i.Status,
			&i.ByteSize,
			&i.DurationMs,
			&i.DetachedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionMediaBySession = `-- name: ListSessionMediaBySession :many
SELECT id, session_id, storage_session_id, workspace_id, kind, media_type, alt, prompt, model, provider_id, source, source_media_id, status, byte_size, duration_ms, detached_at, created_at
FROM session_media
WHERE session_id = ?
  AND status = 'ready'
ORDER BY created_at ASC
`

func (q *Queries) ListSessionMediaBySession(ctx context.Context, sessionID sql.NullString) ([]SessionMedia, error) {
	rows, err := q.db.QueryContext(ctx, listSessionMediaBySession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SessionMedia{}
	for rows.Next() {
		var i SessionMedia
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.StorageSessionID,
			&i.WorkspaceID,
			&i.Kind,
			&i.MediaType,
			&i.Alt,
			&i.Prompt,
			&i.Model,
			&i.ProviderID,
			&i.Source,
			&i.SourceMediaID,
			&i.Status,
			&i.ByteSize,
			&i.DurationMs,
			&i.DetachedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markSessionMediaDeleted = `-- name: MarkSessionMediaDeleted :one
UPDATE session_media
SET status = 'deleted'
WHERE id = ?
  AND status = 'ready'
RETURNING id, session_id, storage_session_id, workspace_id, kind, media_type, alt, prompt, model, provider_id, source, source_media_id, status, byte_size, duration_ms, detached_at, created_at
`

func (q *Queries) MarkSessionMediaDeleted(ctx context.Context, id string) (SessionMedia, error) {
	row := q.db.QueryRowContext(ctx, markSessionMediaDeleted, id)
	var i SessionMedia
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.StorageSessionID,
		&i.WorkspaceID,
		&i.Kind,
		&i.MediaType,
		&i.Alt,
		&i.Prompt,
		&i.Model,
		&i.ProviderID,
		&i.Source,
		&i.SourceMediaID,
		&i.Status,
		&i.ByteSize,
		&i.DurationMs,
		&i.DetachedAt,
		&i.CreatedAt,
	)
	return i, err
}

const updateSessionMediaWorkspace = `-- name: UpdateSessionMediaWorkspace :exec
UPDATE session_media
SET workspace_id = ?
WHERE session_id = ?
`

type UpdateSessionMediaWorkspaceParams struct {
	WorkspaceID sql.NullString `json:"workspace_id"`
	SessionID   sql.NullString `json:"session_id"`
}

func (q *Queries) UpdateSessionMediaWorkspace(ctx context.Context, arg UpdateSessionMediaWorkspaceParams) error {
	_, err := q.db.ExecContext(ctx, updateSessionMediaWorkspace, arg.WorkspaceID, arg.SessionID)
	return err
}
