// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: session_runs.sql

package db

import (
	"context"
)

const acquireSessionRun = `-- name: AcquireSessionRun :execrows
INSERT INTO session_runs (session_id, run_id, owner)
VALUES (?, ?, ?)
ON CONFLICT (session_id) DO NOTHING
`

type AcquireSessionRunParams struct {
	SessionID string `json:"session_id"`
	RunID     string `json:"run_id"`
	Owner     string `json:"owner"`
}

func (q *Queries) AcquireSessionRun(ctx context.Context, arg AcquireSessionRunParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, acquireSessionRun, arg.SessionID, arg.RunID, arg.Owner)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteStaleSessionRun = `-- name: DeleteStaleSessionRun :execrows
DELETE FROM session_runs
WHERE session_id = ? AND updated_at < ?
`

type DeleteStaleSessionRunParams struct {
	SessionID string `json:"session_id"`
	UpdatedAt int64  `json:"updated_at"`
}

func (q *Queries) DeleteStaleSessionRun(ctx context.Context, arg DeleteStaleSessionRunParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteStaleSessionRun, arg.SessionID, arg.UpdatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getSessionRun = `-- name: GetSessionRun :one
SELECT session_id, run_id, owner, abort_requested, updated_at
FROM session_runs
WHERE session_id = ?
`

func (q *Queries) GetSessionRun(ctx context.Context, sessionID string) (SessionRun, error) {
	row := q.db.QueryRowContext(ctx, getSessionRun, sessionID)
	var i SessionRun
	err := row.Scan(
		&i.SessionID,
		&i.RunID,
		&i.Owner,
		&i.AbortRequested,
		&i.UpdatedAt,
	)
	return i, err
}

const heartbeatSessionRun = `-- name: HeartbeatSessionRun :execrows
UPDATE session_runs
SET updated_at = unixepoch ('now', 'subsec') * 1000
WHERE session_id = ? AND run_id = ?
`

type HeartbeatSessionRunParams struct {
	SessionID string `json:"session_id"`
	RunID     string `json:"run_id"`
}

func (q *Queries) HeartbeatSessionRun(ctx context.Context, arg HeartbeatSessionRunParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, heartbeatSessionRun, arg.SessionID, arg.RunID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const releaseSessionRun = `-- name: ReleaseSessionRun :execrows
DELETE FROM session_runs
WHERE session_id = ? AND run_id = ?
`

type ReleaseSessionRunParams struct {
	SessionID string `json:"session_id"`
	RunID     string `json:"run_id"`
}

func (q *Queries) ReleaseSessionRun(ctx context.Context, arg ReleaseSessionRunParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, releaseSessionRun, arg.SessionID, arg.RunID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const requestSessionRunAbort = `-- name: RequestSessionRunAbort :execrows
UPDATE session_runs
SET
    abort_requested = 1,
    updated_at = unixepoch ('now', 'subsec') * 1000
WHERE session_id = ?
`

func (q *Queries) RequestSessionRunAbort(ctx context.Context, sessionID string) (int64, error) {
	result, err := q.db.ExecContext(ctx, requestSessionRunAbort, sessionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const sessionRunExists = `-- name: SessionRunExists :one
SELECT EXISTS (
    SELECT 1
    FROM session_runs
    WHERE session_id = ?
)
`

func (q *Queries) SessionRunExists(ctx context.Context, sessionID string) (bool, error) {
	row := q.db.QueryRowContext(ctx, sessionRunExists, sessionID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
