// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: skill_curator.sql

package db

import (
	"context"
)

const countSessionRuns = `-- name: CountSessionRuns :one
SELECT count(*)
FROM session_runs
`

func (q *Queries) CountSessionRuns(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSessionRuns)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteSkillCuratorState = `-- name: DeleteSkillCuratorState :exec
DELETE FROM skill_curator_state
WHERE skill_name = ?
`

func (q *Queries) DeleteSkillCuratorState(ctx context.Context, skillName string) error {
	_, err := q.db.ExecContext(ctx, deleteSkillCuratorState, skillName)
	return err
}

const ensureSkillCuratorPass = `-- name: EnsureSkillCuratorPass :exec
INSERT INTO skill_curator_pass (id, last_pass_at, last_merge_at, runs_idle_since)
VALUES (1, 0, 0, 0)
ON CONFLICT (id) DO NOTHING
`

func (q *Queries) EnsureSkillCuratorPass(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, ensureSkillCuratorPass)
	return err
}

const getSkillCuratorPass = `-- name: GetSkillCuratorPass :one
SELECT id, last_pass_at, last_merge_at, runs_idle_since
FROM skill_curator_pass
WHERE id = 1
`

func (q *Queries) GetSkillCuratorPass(ctx context.Context) (SkillCuratorPass, error) {
	row := q.db.QueryRowContext(ctx, getSkillCuratorPass)
	var i SkillCuratorPass
	err := row.Scan(
		&i.ID,
		&i.LastPassAt,
		&i.LastMergeAt,
		&i.RunsIdleSince,
	)
	return i, err
}

const getSkillCuratorState = `-- name: GetSkillCuratorState :one
SELECT skill_name, origin, status, pinned, created_at, last_used_at, unused_since, archived_at, pinned_at, delete_notified_at
FROM skill_curator_state
WHERE skill_name = ?
`

func (q *Queries) GetSkillCuratorState(ctx context.Context, skillName string) (SkillCuratorState, error) {
	row := q.db.QueryRowContext(ctx, getSkillCuratorState, skillName)
	var i SkillCuratorState
	err := row.Scan(
		&i.SkillName,
		&i.Origin,
		&i.Status,
		&i.Pinned,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.UnusedSince,
		&i.ArchivedAt,
		&i.PinnedAt,
		&i.DeleteNotifiedAt,
	)
	return i, err
}

const listSkillCuratorStates = `-- name: ListSkillCuratorStates :many
SELECT skill_name, origin, status, pinned, created_at, last_used_at, unused_since, archived_at, pinned_at, delete_notified_at
FROM skill_curator_state
ORDER BY skill_name
`

func (q *Queries) ListSkillCuratorStates(ctx context.Context) ([]SkillCuratorState, error) {
	rows, err := q.db.QueryContext(ctx, listSkillCuratorStates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SkillCuratorState{}
	for rows.Next() {
		var i SkillCuratorState
		if err := rows.Scan(
			&i.SkillName,
			&i.Origin,
			&i.Status,
			&i.Pinned,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.UnusedSince,
			&i.ArchivedAt,
			&i.PinnedAt,
			&i.DeleteNotifiedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setCuratorRunsIdleSince = `-- name: SetCuratorRunsIdleSince :exec
UPDATE skill_curator_pass
SET runs_idle_since = ?
WHERE id = 1
`

func (q *Queries) SetCuratorRunsIdleSince(ctx context.Context, runsIdleSince int64) error {
	_, err := q.db.ExecContext(ctx, setCuratorRunsIdleSince, runsIdleSince)
	return err
}

const updateSkillCuratorPass = `-- name: UpdateSkillCuratorPass :exec
UPDATE skill_curator_pass
SET
    last_pass_at = ?,
    last_merge_at = ?,
    runs_idle_since = ?
WHERE id = 1
`

type UpdateSkillCuratorPassParams struct {
	LastPassAt    int64 `json:"last_pass_at"`
	LastMergeAt   int64 `json:"last_merge_at"`
	RunsIdleSince int64 `json:"runs_idle_since"`
}

func (q *Queries) UpdateSkillCuratorPass(ctx context.Context, arg UpdateSkillCuratorPassParams) error {
	_, err := q.db.ExecContext(ctx, updateSkillCuratorPass, arg.LastPassAt, arg.LastMergeAt, arg.RunsIdleSince)
	return err
}

const upsertSkillCuratorState = `-- name: UpsertSkillCuratorState :exec
INSERT INTO skill_curator_state (
    skill_name,
    origin,
    status,
    pinned,
    created_at,
    last_used_at,
    unused_since,
    archived_at,
    pinned_at,
    delete_notified_at
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (skill_name) DO UPDATE
SET
    status = excluded.status,
    pinned = excluded.pinned,
    last_used_at = excluded.last_used_at,
    unused_since = excluded.unused_since,
    archived_at = excluded.archived_at,
    pinned_at = excluded.pinned_at,
    delete_notified_at = excluded.delete_notified_at
`

type UpsertSkillCuratorStateParams struct {
	SkillName        string `json:"skill_name"`
	Origin           string `json:"origin"`
	Status           string `json:"status"`
	Pinned           int64  `json:"pinned"`
	CreatedAt        int64  `json:"created_at"`
	LastUsedAt       int64  `json:"last_used_at"`
	UnusedSince      int64  `json:"unused_since"`
	ArchivedAt       int64  `json:"archived_at"`
	PinnedAt         int64  `json:"pinned_at"`
	DeleteNotifiedAt int64  `json:"delete_notified_at"`
}

func (q *Queries) UpsertSkillCuratorState(ctx context.Context, arg UpsertSkillCuratorStateParams) error {
	_, err := q.db.ExecContext(ctx, upsertSkillCuratorState,
		arg.SkillName,
		arg.Origin,
		arg.Status,
		arg.Pinned,
		arg.CreatedAt,
		arg.LastUsedAt,
		arg.UnusedSince,
		arg.ArchivedAt,
		arg.PinnedAt,
		arg.DeleteNotifiedAt,
	)
	return err
}
