// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: usage.sql

package db

import (
	"context"
	"database/sql"
)

const countUsageEventsInRange = `-- name: CountUsageEventsInRange :one
SELECT COUNT(*)
FROM usage_events
WHERE usage_events.created_at >= ?1
  AND usage_events.created_at < ?2
  AND (
    ?3 IS NULL
    OR usage_events.workspace_id = ?3
    OR usage_events.session_id IN (
      SELECT id FROM sessions WHERE workspace_id = ?3
    )
  )
`

type CountUsageEventsInRangeParams struct {
	FromMs      int64       `json:"from_ms"`
	ToMs        int64       `json:"to_ms"`
	WorkspaceID interface{} `json:"workspace_id"`
}

func (q *Queries) CountUsageEventsInRange(ctx context.Context, arg CountUsageEventsInRangeParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsageEventsInRange, arg.FromMs, arg.ToMs, arg.WorkspaceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteUsageEventsBefore = `-- name: DeleteUsageEventsBefore :execrows
DELETE FROM usage_events
WHERE created_at < ?1
`

func (q *Queries) DeleteUsageEventsBefore(ctx context.Context, beforeMs int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteUsageEventsBefore, beforeMs)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const insertUsageEvent = `-- name: InsertUsageEvent :exec
INSERT INTO usage_events (
    id,
    created_at,
    workspace_id,
    session_id,
    provider_id,
    model_id,
    call_kind,
    input_tokens,
    output_tokens,
    cache_read,
    cache_write
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertUsageEventParams struct {
	ID           string         `json:"id"`
	CreatedAt    int64          `json:"created_at"`
	WorkspaceID  sql.NullString `json:"workspace_id"`
	SessionID    sql.NullString `json:"session_id"`
	ProviderID   string         `json:"provider_id"`
	ModelID      string         `json:"model_id"`
	CallKind     string         `json:"call_kind"`
	InputTokens  int64          `json:"input_tokens"`
	OutputTokens int64          `json:"output_tokens"`
	CacheRead    int64          `json:"cache_read"`
	CacheWrite   int64          `json:"cache_write"`
}

func (q *Queries) InsertUsageEvent(ctx context.Context, arg InsertUsageEventParams) error {
	_, err := q.db.ExecContext(ctx, insertUsageEvent,
		arg.ID,
		arg.CreatedAt,
		arg.WorkspaceID,
		arg.SessionID,
		arg.ProviderID,
		arg.ModelID,
		arg.CallKind,
		arg.InputTokens,
		arg.OutputTokens,
		arg.CacheRead,
		arg.CacheWrite,
	)
	return err
}

const listUsageEventsInRange = `-- name: ListUsageEventsInRange :many
SELECT usage_events.id, usage_events.created_at, usage_events.workspace_id, usage_events.session_id, usage_events.provider_id, usage_events.model_id, usage_events.call_kind, usage_events.input_tokens, usage_events.output_tokens, usage_events.cache_read, usage_events.cache_write
FROM usage_events
WHERE usage_events.created_at >= ?1
  AND usage_events.created_at < ?2
  AND (
    ?3 IS NULL
    OR usage_events.workspace_id = ?3
    OR usage_events.session_id IN (
      SELECT id FROM sessions WHERE workspace_id = ?3
    )
  )
ORDER BY usage_events.created_at ASC
`

type ListUsageEventsInRangeParams struct {
	FromMs      int64       `json:"from_ms"`
	ToMs        int64       `json:"to_ms"`
	WorkspaceID interface{} `json:"workspace_id"`
}

func (q *Queries) ListUsageEventsInRange(ctx context.Context, arg ListUsageEventsInRangeParams) ([]UsageEvent, error) {
	rows, err := q.db.QueryContext(ctx, listUsageEventsInRange, arg.FromMs, arg.ToMs, arg.WorkspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UsageEvent{}
	for rows.Next() {
		var i UsageEvent
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.WorkspaceID,
			&i.SessionID,
			&i.ProviderID,
			&i.ModelID,
			&i.CallKind,
			&i.InputTokens,
			&i.OutputTokens,
			&i.CacheRead,
			&i.CacheWrite,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsageEventsPage = `-- name: ListUsageEventsPage :many
SELECT usage_events.id, usage_events.created_at, usage_events.workspace_id, usage_events.session_id, usage_events.provider_id, usage_events.model_id, usage_events.call_kind, usage_events.input_tokens, usage_events.output_tokens, usage_events.cache_read, usage_events.cache_write
FROM usage_events
WHERE usage_events.created_at >= ?1
  AND usage_events.created_at < ?2
  AND (
    ?3 IS NULL
    OR usage_events.workspace_id = ?3
    OR usage_events.session_id IN (
      SELECT id FROM sessions WHERE workspace_id = ?3
    )
  )
ORDER BY usage_events.created_at DESC
LIMIT ?5
OFFSET ?4
`

type ListUsageEventsPageParams struct {
	FromMs      int64       `json:"from_ms"`
	ToMs        int64       `json:"to_ms"`
	WorkspaceID interface{} `json:"workspace_id"`
	Offset      int64       `json:"offset"`
	Limit       int64       `json:"limit"`
}

func (q *Queries) ListUsageEventsPage(ctx context.Context, arg ListUsageEventsPageParams) ([]UsageEvent, error) {
	rows, err := q.db.QueryContext(ctx, listUsageEventsPage,
		arg.FromMs,
		arg.ToMs,
		arg.WorkspaceID,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UsageEvent{}
	for rows.Next() {
		var i UsageEvent
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.WorkspaceID,
			&i.SessionID,
			&i.ProviderID,
			&i.ModelID,
			&i.CallKind,
			&i.InputTokens,
			&i.OutputTokens,
			&i.CacheRead,
			&i.CacheWrite,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
